#!/bin/bash

password_file="passwords.txt"

add_password() {
    echo "サービス名を入力してください:"
    read service_name
    echo "ユーザー名を入力してください:"
    read username
    echo "パスワードを入力してください:"
    read password

    echo "$service_name:$username:$password" >> "$password_file"
    echo "パスワードの追加は成功しました。"
}

    get_password() {
    echo "サービス名を入力してください:"
    read service_name

    service_info=$(grep "^$service_name:" "$password_file")

    if [ -z "$service_info" ]; then
        echo "そのサービスは登録されていません。"
    else
        IFS=':' read -ra info <<< "$service_info"
        echo "サービス名：${info[0]}"
        echo "ユーザー名：${info[1]}"
        echo "パスワード：${info[2]}"
    fi
}

while true; do
    echo "パスワードマネージャーへようこそ！"
    echo "次の選択肢から入力してください(Add Password/Get Password/Exit)："
    read choice

    case "$choice" in
        "Add Password")
            add_password
            ;;
        "Get Password")
            get_password
            ;;
        "Exit")
            echo "Thank you!"
            break
            ;;
        *)
            echo "入力が間違えています。Add Password/Get Password/Exit から入力してください。"
            ;;
    esac
done
